server:
  #  port: 3389
  port: 8888
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
    #    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/erp_pro?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&rewriteBatchedStatements =true
    #    url: jdbc:mysql://127.0.0.1:3306/erp_pro?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    #    url: jdbc\:mysql\://127.0.0.1\:3306/wy_gow?useUnicode\=true&characterEncoding\=utf8
    username: root
    password: mysql
    initialSize: 16
    minIdle: 16
  maxActive: 32
  maxWait: 60000
#  redis:
#    host: 8.131.84.129
#    port: 6379
#    database: 0
#    password: cloud_redis
#  #连接池最大连接数（使用负值表示没有限制）
#  spring.redis.jedis.pool.max-active=8
#  # 连接池最大阻塞等待时间（使用负值表示没有限制）
#  spring.redis.jedis.pool.max-wait=-1
#  # 连接池中的最大空闲连接
#  spring.redis.jedis.pool.max-idle=8
#  # 连接池中的最小空闲连接
#  spring.redis.jedis.pool.min-idle=0

## test for revert commit --amend
## commit --amend  first  total